version: "3"
services:
  mongodb:
    image: mongo
    container_name: database
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - database_data_volume:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - client-db
  client-rest:
    container_name: client
    build:
      context: ./test-nextjs-golang-graphql-back-client-2022
      dockerfile: Dockerfile
    ports:
      - 3200:3200
    depends_on:
      - mongodb
    networks:
      - client-db
      - server-client
    restart: on-failure

  server-graphql:
    container_name: server
    build:
      context: ./test-nextjs-golang-graphql-back-server-2022
      dockerfile: Dockerfile
    ports:
      - 3201:3201
    networks:
      - front-server
      - server-client
  web-app:
    container_name: front
    build:
      context: ./test-nextjs-golang-graphql-new-front-2022
      dockerfile:  Dockerfile
    ports:
      - 3000:3000
    networks:
      - front-server
networks:
  front-server:
    driver: bridge
  server-client:
    driver: bridge
  client-db:
    driver: bridge

volumes:
  database_data_volume:
