version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /test-nextjs-golang/mongo/database:/data/db
    ports:
      - 27017:27017
  server:
    image: golang:1.16-alpine
    working_dir: /app
    command:
